#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# A Bash script the shows the domains and subdomains connected to your servers.

# Function to retreive & display information about a subdomain
display_subdomain_info() {
    local subdomain=$1
    local record_type=$2
    local ip_address=$3
    local destination=$(dig +short $ip_address)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check the number of arguments passed staright to the script
if [[ -z $1 ]]; then
    echo "Domain argument is mandatory"
    exit 1
fi

domain=$1
subdomain=$2

# Display the information for the default subdomains if subdomain argument is not given
if [[ -z $subdomain ]]; then
    display_subdomain_info "www" "A" "www.$domain"
    display_subdomain_info "lb-01" "A" "lb-01.$domain"
    display_subdomain_info "web-01" "A" "web-01.$domain"
    display_subdomain_info "web-02" "A" "web-02.$domain"
else
    # Display information for the specified subdomain
    case $subdomain in
        www)
            display_subdomain_info "www" "A" "www.$domain"
            ;;
        lb-01)
            display_subdomain_info "lb-01" "A" "lb-01.$domain"
            ;;
        web-01)
            display_subdomain_info "web-01" "A" "web-01.$domain"
            ;;
        web-02)
            display_subdomain_info "web-02" "A" "web-02.$domain"
            ;;
        *)
            echo "Invalid subdomain: $subdomain"
            ;;
    esac
fi
